name: "Java CI with Maven - Documentation"

on:
  pull_request:
    types:
      - closed
    
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: "Se placer dans le dépôt courant"
        uses: actions/checkout@v4
      
      - name: "Configurer Java JDK 21"
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: "Générer la documentation avec Maven"
        run: mvn -B javadoc::javadoc

      - name: "Déployer la documentation sur GitHub Pages"
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          commit_message: 'Update Javadoc'